name       : mongosh
version    : 1.1.1
release    : 3
source     :
    - https://github.com/mongodb-js/mongosh/archive/refs/tags/v1.1.1.tar.gz : 1c27760091f211fa6e0f3806be2c0c69cd25726017a243735225cd720781bdeb
homepage   : https://docs.mongodb.com/mongodb-shell/
license    : Apache-2.0
component  : database
summary    : The MongoDB Shell Interpreter
description: |
    The MongoDB Shell, mongosh, is a fully functional JavaScript and Node.js 14.x REPL environment for interacting with MongoDB deployments.
networking : yes
builddeps  :
    - pkgconfig(krb5)
    - pkgconfig(libuv)
    - git
    - jq
    - nodejs-devel
    - yarn
rundeps    :
    - nodejs
setup      : |
    sed -i "/electron-notarize/d" package.json
    %patch -p1 < $pkgfiles/dont-effing-use-the-damned-notarize.patch
    %patch -p1 < $pkgfiles/build-pull-your-dump-together.patch
    rm packages/build/src/packaging/macos-sign*
    jq 'del(.dependencies."electron-notarize")' package-lock.json > package-tmp.json
    mv package-{tmp,lock}.json
    yarn import
build      : |
    yarn --check-files
    yarn run bootstrap
    yarn run compile-cli
    yarn --production --check-files
install    : |
    install -dm00755 $installdir/usr/bin
    install -dm00755 $installdir/usr/lib/node_modules/mongosh
    cp -R packages node_modules package*.json $installdir/usr/lib/node_modules/mongosh
    ln -s /usr/lib/node_modules/mongosh/packages/cli-repl/bin/mongosh.js $installdir/usr/bin/mongosh
